name: Anna Northwood
favicon: null
layout_spectrum: 0.1637946565169841
typography_spectrum: 0.0547825254034251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.02331292489543557
  lightness: 0.7793047667946666
  saturation: 0.09829276497475803
  rhythmicContrast: 0.12171961995773017
purpose: []
