name: Anna Northwood
favicon: null
layout_spectrum: 0.6707
typography_spectrum: 0.14208
title: Creative Art Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161614'
    - '#a3a29e'
    - '#333331'
    - '#868581'
    - '#63625e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
